


	/**
	 *
	 * @author Jasmin
	 */
	public class MainGui extends javax.swing.JFrame {
	    static public String convertUrlToJavaPackageName(String url)
	    {
	        String packageName;
	        //firstly removed http://
	        packageName = url.replaceFirst("http://", "");
	        //the strip the last / if it has one
	        if (packageName.endsWith("/"))
	        {
	            //yes - so remove it
	            packageName = packageName.substring(0, packageName.length()-1);
	        }
	        //now split the packagename
	        String[] parts = packageName.split("\\.");
	        packageName = "";
	        //now flip reverse to java standards
	        //loop through in reverse order, as is the standard for Java packagenames
	        for (int loop = parts.length - 1; loop > -1; loop--)
	        {
	            //path string
	            packageName = packageName + "." + parts[loop];
	        }
	        //remove . from begining
	        packageName = packageName.substring(1);
	        return packageName;
	    }
	    /**
	     * Creates new form WSDL2CodeApp
	     */
	    public MainGui() {
	        initComponents();
	        setLocationRelativeTo(null);
	        setVisible(true);
	        setTitle("WSDL2JavaCodeApp");
	        setResizable(false);
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	    private void initComponents() {

	        ChooseFile = new javax.swing.JFileChooser();
	        jLabel1 = new javax.swing.JLabel();
	        edtUrl = new javax.swing.JTextField();
	        jLabel2 = new javax.swing.JLabel();
	        edtOutput = new javax.swing.JTextField();
	        jLabel3 = new javax.swing.JLabel();
	        edtPackage = new javax.swing.JTextField();
	        btnBrowse = new javax.swing.JButton();
	        btnProcess = new javax.swing.JButton();

	        ChooseFile.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
	        ChooseFile.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
	        ChooseFile.setBorder(javax.swing.BorderFactory.createEtchedBorder());
	        ChooseFile.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
	        ChooseFile.setPreferredSize(new java.awt.Dimension(800, 500));

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
	        jLabel1.setText("Url");

	        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
	        jLabel2.setText("Output Folder");

	        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
	        jLabel3.setText("Package Name");

	        btnBrowse.setText("Browse");
	        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btnBrowseActionPerformed(evt);
	            }
	        });

	        btnProcess.setText("Process");
	        btnProcess.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btnProcessActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(21, 21, 21)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(edtPackage, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(btnProcess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(edtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
	                    .addComponent(edtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel2)
	                    .addComponent(jLabel3))
	                .addContainerGap(23, Short.MAX_VALUE))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(20, 20, 20)
	                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(edtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(edtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(edtPackage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(btnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addContainerGap(32, Short.MAX_VALUE))
	        );

	        pack();
	    }// </editor-fold>//GEN-END:initComponents

	    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
	        
	    	/*AppConfig appConfig = new AppConfig ();
	        appConfig.setURL(uRL);
	        AppConfig.OutputFolder = edtOutput.getText();
	        SettingsHelper.Packagename = edtPackage.getText();
	        SettingsHelper.SaveSettings();
	        WSDLParser.ProcessWSDL();*/
	        String packageName;

	        if (edtPackage.getText().length() != 0)
	        {
	            packageName = edtPackage.getText();
	        }
	        else
	        {
	            //packageName =  convertUrlToJavaPackageName(PropertyContainer.Namespace);
	        }
	        //if (/*FileHelper.createFolderStructure(edtOutput.getText(), packageName)*/)
	        {
	            try
	            {
	                //folder structure created  continue processing
	                // create service file
	                System.out.println("heeeeeeee");
	                /*Class.CreateServiceClass(packageName);
	                //prepare baseobject
	                Class.CreateBaseObjectFile(packageName);
	                //prepare array object
	                Class.CreateLiteralVectorArrayFile(packageName);
	                //create classes
	                Class.CreateClasess(packageName);
	                //create paramter and return class
	                Class.CreateMethodClasses(packageName);*/
	            }
	            catch (Exception ex)
	            {
	                System.out.print(ex.getMessage());
	            }
	        }
	    }//GEN-LAST:event_btnProcessActionPerformed

	    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
	        ChooseFile.showOpenDialog(this);
	        edtOutput.setText(ChooseFile.getSelectedFile().getAbsolutePath());
	    }//GEN-LAST:event_btnBrowseActionPerformed
	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new MainGui().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify//GEN-BEGIN:variables
	    private javax.swing.JFileChooser ChooseFile;
	    private javax.swing.JButton btnBrowse;
	    private javax.swing.JButton btnProcess;
	    private javax.swing.JTextField edtOutput;
	    private javax.swing.JTextField edtPackage;
	    private javax.swing.JTextField edtUrl;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    // End of variables declaration//GEN-END:variables
	}


